[
  {
    web_pages: ["http://www.unidu.hr/"],
    country: "Croatia",
    "state-province": null,
    domains: ["unidu.hr"],
    name: "University of Dubrovnik",
    alpha_two_code: "HR",
  },
  {
    web_pages: ["http://www.unios.hr/"],
    country: "Croatia",
    "state-province": null,
    domains: ["unios.hr"],
    name: "University of Osijek",
    alpha_two_code: "HR",
  },
  {
    web_pages: ["http://www.unipu.hr/"],
    country: "Croatia",
    "state-province": null,
    domains: ["unipu.hr"],
    name: "University of Pula",
    alpha_two_code: "HR",
  },
  {
    web_pages: ["http://www.uniri.hr/"],
    country: "Croatia",
    "state-province": null,
    domains: ["uniri.hr"],
    name: "University of Rijeka",
    alpha_two_code: "HR",
  },
  {
    web_pages: ["http://www.unist.hr/"],
    country: "Croatia",
    "state-province": null,
    domains: ["unist.hr"],
    name: "University of Split",
    alpha_two_code: "HR",
  },
  {
    web_pages: ["http://www.unizd.hr/"],
    country: "Croatia",
    "state-province": null,
    domains: ["unizd.hr"],
    name: "University of Zadar",
    alpha_two_code: "HR",
  },
  {
    web_pages: ["http://www.unizg.hr/"],
    country: "Croatia",
    "state-province": null,
    domains: ["unizg.hr"],
    name: "University of Zagreb",
    alpha_two_code: "HR",
  },
  {
    web_pages: ["http://www.zsem.hr/"],
    country: "Croatia",
    "state-province": null,
    domains: ["zsem.hr"],
    name: "Zagreb School of Economics and Management",
    alpha_two_code: "HR",
  },
  {
    web_pages: ["http://www.vern.hr/"],
    country: "Croatia",
    "state-province": null,
    domains: ["vern.hr"],
    name: "VERN' University of Applied Sciences",
    alpha_two_code: "HR",
  },
  {
    web_pages: ["http://www.tvz.hr/"],
    country: "Croatia",
    "state-province": null,
    domains: ["tvz.hr"],
    name: "Zagreb University of Applied Sciences",
    alpha_two_code: "HR",
  },
  {
    web_pages: ["http://www.algebra.hr/"],
    country: "Croatia",
    "state-province": null,
    domains: ["algebra.hr"],
    name: "Algebra University College",
    alpha_two_code: "HR",
  },
  {
    web_pages: ["http://www.unin.hr/"],
    country: "Croatia",
    "state-province": null,
    domains: ["unin.hr"],
    name: "University North",
    alpha_two_code: "HR",
  },
];
